"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

var = 0
var1 = 1
temp = 0
while var1 < 4000000:
        var+=var1
        var^=var1
        var1^=var
        var^=var1
        if var%2 == 0:
                temp+=var
                print 'even', + temp
        print var


def fibo(var):
        print var
        if var > 2:
                print fibo(var-1) + fibo(var-2)
        else:
                return var